version: '3'
services:
  web:
    build:
      context: .
      args:
        TIMEZONE: UTC
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - web_data:/var/www/html
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zencart
      MYSQL_DATABASE: zencart
      MYSQL_USER: zencart
      MYSQL_PASSWORD: zencart
    ports:
      - 3306:3306
volumes:
  db_data:
  web_data:
